version: "3"
services:
  transfer-api:
    container_name: transfer-api_dev
    env_file: 
      - .env   
    build: ./
    depends_on: 
      - "db"
    ports:
      - '9011:${PORT}'
    volumes:
      - ./:/go/src/github.com/julioshinoda/transfer-api
  db:
    image: "postgres:11"
    container_name: "transfer-db"
    environment:
      - POSTGRES_USER=transfer
      - POSTGRES_PASSWORD=transfer
      - POSTGRES_DB=transfer
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data    